### ISSUE TITLE
Difference between mc200c2_original_fw.bin and msc313ebootrom.bin

### ISSUE THREAD

**Issue by jaytxrx** [fifteenhex/mc200c2camerahacks#1]
What is the difference between mc200c2_original_fw.bin and msc313ebootrom.bin ?

As per my understanding, msc313ebootrom.bin is present inside mc200c2_original_fw.bin. Is this true ? I tried to search the contents of msc313ebootrom.bin inside mc200c2_original_fw.bin, but couldn't find.

How did you get msc313ebootrom.bin ? Do you also have the dump of the spi flash ?

**Comment by fifteenhex** [comment]
msc313ebootrom is the internal rom from the chip itself. mc200c2_original_fw.bin is a dump of the spi nor flash taken via uboot's md command.

**Comment by jaytxrx** [comment]
Does this mean that the contents of msc313ebootrom will be visible inside  mc200c2_original_fw.bin ?

**Comment by fifteenhex** [comment]
No as bootrom is already in the chip. In the mc200c2_original_fw.bin is two loader blobs that come before uboot, uboot itself, the kernel and the rootfs.

**Comment by jaytxrx** [comment]
How did you dump msc313ebootrom ?

**Comment by fifteenhex** [comment]
Using uboot. It's mapped into the start of the address space.
